package com.outdu.camconnect.ui.models

data class CountryCode(
    val code: String,
    val name: String
) {
    val displayName: String
        get() = "$code - $name"
        
    companion object {
        val VALID_CODES = listOf(
            CountryCode("AF", "Afghanistan"),
            CountryCode("AX", "Åland Islands"),
            CountryCode("AL", "Albania"),
            CountryCode("DZ", "Algeria"),
            CountryCode("AS", "American Samoa"),
            CountryCode("AD", "Andorra"),
            CountryCode("AO", "Angola"),
            CountryCode("AI", "Anguilla"),
            CountryCode("AQ", "Antarctica"),
            CountryCode("AG", "Antigua and Barbuda"),
            CountryCode("AR", "Argentina"),
            CountryCode("AM", "Armenia"),
            CountryCode("AW", "Aruba"),
            CountryCode("AU", "Australia"),
            CountryCode("AT", "Austria"),
            CountryCode("AZ", "Azerbaijan"),
            CountryCode("BS", "Bahamas"),
            CountryCode("BH", "Bahrain"),
            CountryCode("BD", "Bangladesh"),
            CountryCode("BB", "Barbados"),
            CountryCode("BY", "Belarus"),
            CountryCode("BE", "Belgium"),
            CountryCode("BZ", "Belize"),
            CountryCode("BJ", "Benin"),
            CountryCode("BM", "Bermuda"),
            CountryCode("BT", "Bhutan"),
            CountryCode("BO", "Bolivia"),
            CountryCode("BQ", "Bonaire, Sint Eustatius and Saba"),
            CountryCode("BA", "Bosnia and Herzegovina"),
            CountryCode("BW", "Botswana"),
            CountryCode("BV", "Bouvet Island"),
            CountryCode("BR", "Brazil"),
            CountryCode("IO", "British Indian Ocean Territory"),
            CountryCode("BN", "Brunei Darussalam"),
            CountryCode("BG", "Bulgaria"),
            CountryCode("BF", "Burkina Faso"),
            CountryCode("BI", "Burundi"),
            CountryCode("CV", "Cabo Verde"),
            CountryCode("KH", "Cambodia"),
            CountryCode("CM", "Cameroon"),
            CountryCode("CA", "Canada"),
            CountryCode("KY", "Cayman Islands"),
            CountryCode("CF", "Central African Republic"),
            CountryCode("TD", "Chad"),
            CountryCode("CL", "Chile"),
            CountryCode("CN", "China"),
            CountryCode("CX", "Christmas Island"),
            CountryCode("CC", "Cocos (Keeling) Islands"),
            CountryCode("CO", "Colombia"),
            CountryCode("KM", "Comoros"),
            CountryCode("CG", "Congo"),
            CountryCode("CD", "Congo (Democratic Republic of the)"),
            CountryCode("CK", "Cook Islands"),
            CountryCode("CR", "Costa Rica"),
            CountryCode("CI", "Côte d'Ivoire"),
            CountryCode("HR", "Croatia"),
            CountryCode("CU", "Cuba"),
            CountryCode("CW", "Curaçao"),
            CountryCode("CY", "Cyprus"),
            CountryCode("CZ", "Czechia"),
            CountryCode("DK", "Denmark"),
            CountryCode("DJ", "Djibouti"),
            CountryCode("DM", "Dominica"),
            CountryCode("DO", "Dominican Republic"),
            CountryCode("EC", "Ecuador"),
            CountryCode("EG", "Egypt"),
            CountryCode("SV", "El Salvador"),
            CountryCode("GQ", "Equatorial Guinea"),
            CountryCode("ER", "Eritrea"),
            CountryCode("EE", "Estonia"),
            CountryCode("SZ", "Eswatini"),
            CountryCode("ET", "Ethiopia"),
            CountryCode("FK", "Falkland Islands (Malvinas)"),
            CountryCode("FO", "Faroe Islands"),
            CountryCode("FJ", "Fiji"),
            CountryCode("FI", "Finland"),
            CountryCode("FR", "France"),
            CountryCode("GF", "French Guiana"),
            CountryCode("PF", "French Polynesia"),
            CountryCode("TF", "French Southern Territories"),
            CountryCode("GA", "Gabon"),
            CountryCode("GM", "Gambia"),
            CountryCode("GE", "Georgia"),
            CountryCode("DE", "Germany"),
            CountryCode("GH", "Ghana"),
            CountryCode("GI", "Gibraltar"),
            CountryCode("GR", "Greece"),
            CountryCode("GL", "Greenland"),
            CountryCode("GD", "Grenada"),
            CountryCode("GP", "Guadeloupe"),
            CountryCode("GU", "Guam"),
            CountryCode("GT", "Guatemala"),
            CountryCode("GG", "Guernsey"),
            CountryCode("GN", "Guinea"),
            CountryCode("GW", "Guinea-Bissau"),
            CountryCode("GY", "Guyana"),
            CountryCode("HT", "Haiti"),
            CountryCode("HM", "Heard Island and McDonald Islands"),
            CountryCode("VA", "Holy See"),
            CountryCode("HN", "Honduras"),
            CountryCode("HK", "Hong Kong"),
            CountryCode("HU", "Hungary"),
            CountryCode("IS", "Iceland"),
            CountryCode("IN", "India"),
            CountryCode("ID", "Indonesia"),
            CountryCode("IR", "Iran"),
            CountryCode("IQ", "Iraq"),
            CountryCode("IE", "Ireland"),
            CountryCode("IM", "Isle of Man"),
            CountryCode("IL", "Israel"),
            CountryCode("IT", "Italy"),
            CountryCode("JM", "Jamaica"),
            CountryCode("JP", "Japan"),
            CountryCode("JE", "Jersey"),
            CountryCode("JO", "Jordan"),
            CountryCode("KZ", "Kazakhstan"),
            CountryCode("KE", "Kenya"),
            CountryCode("KI", "Kiribati"),
            CountryCode("KP", "Korea (North)"),
            CountryCode("KR", "Korea (South)"),
            CountryCode("KW", "Kuwait"),
            CountryCode("KG", "Kyrgyzstan"),
            CountryCode("LA", "Laos"),
            CountryCode("LV", "Latvia"),
            CountryCode("LB", "Lebanon"),
            CountryCode("LS", "Lesotho"),
            CountryCode("LR", "Liberia"),
            CountryCode("LY", "Libya"),
            CountryCode("LI", "Liechtenstein"),
            CountryCode("LT", "Lithuania"),
            CountryCode("LU", "Luxembourg"),
            CountryCode("MO", "Macao"),
            CountryCode("MG", "Madagascar"),
            CountryCode("MW", "Malawi"),
            CountryCode("MY", "Malaysia"),
            CountryCode("MV", "Maldives"),
            CountryCode("ML", "Mali"),
            CountryCode("MT", "Malta"),
            CountryCode("MH", "Marshall Islands"),
            CountryCode("MQ", "Martinique"),
            CountryCode("MR", "Mauritania"),
            CountryCode("MU", "Mauritius"),
            CountryCode("YT", "Mayotte"),
            CountryCode("MX", "Mexico"),
            CountryCode("FM", "Micronesia"),
            CountryCode("MD", "Moldova"),
            CountryCode("MC", "Monaco"),
            CountryCode("MN", "Mongolia"),
            CountryCode("ME", "Montenegro"),
            CountryCode("MS", "Montserrat"),
            CountryCode("MA", "Morocco"),
            CountryCode("MZ", "Mozambique"),
            CountryCode("MM", "Myanmar"),
            CountryCode("NA", "Namibia"),
            CountryCode("NR", "Nauru"),
            CountryCode("NP", "Nepal"),
            CountryCode("NL", "Netherlands"),
            CountryCode("NC", "New Caledonia"),
            CountryCode("NZ", "New Zealand"),
            CountryCode("NI", "Nicaragua"),
            CountryCode("NE", "Niger"),
            CountryCode("NG", "Nigeria"),
            CountryCode("NU", "Niue"),
            CountryCode("NF", "Norfolk Island"),
            CountryCode("MK", "North Macedonia"),
            CountryCode("MP", "Northern Mariana Islands"),
            CountryCode("NO", "Norway"),
            CountryCode("OM", "Oman"),
            CountryCode("PK", "Pakistan"),
            CountryCode("PW", "Palau"),
            CountryCode("PS", "Palestine"),
            CountryCode("PA", "Panama"),
            CountryCode("PG", "Papua New Guinea"),
            CountryCode("PY", "Paraguay"),
            CountryCode("PE", "Peru"),
            CountryCode("PH", "Philippines"),
            CountryCode("PN", "Pitcairn"),
            CountryCode("PL", "Poland"),
            CountryCode("PT", "Portugal"),
            CountryCode("PR", "Puerto Rico"),
            CountryCode("QA", "Qatar"),
            CountryCode("RE", "Réunion"),
            CountryCode("RO", "Romania"),
            CountryCode("RU", "Russia"),
            CountryCode("RW", "Rwanda"),
            CountryCode("BL", "Saint Barthélemy"),
            CountryCode("SH", "Saint Helena"),
            CountryCode("KN", "Saint Kitts and Nevis"),
            CountryCode("LC", "Saint Lucia"),
            CountryCode("MF", "Saint Martin (French part)"),
            CountryCode("PM", "Saint Pierre and Miquelon"),
            CountryCode("VC", "Saint Vincent and the Grenadines"),
            CountryCode("WS", "Samoa"),
            CountryCode("SM", "San Marino"),
            CountryCode("ST", "São Tomé and Príncipe"),
            CountryCode("SA", "Saudi Arabia"),
            CountryCode("SN", "Senegal"),
            CountryCode("RS", "Serbia"),
            CountryCode("SC", "Seychelles"),
            CountryCode("SL", "Sierra Leone"),
            CountryCode("SG", "Singapore"),
            CountryCode("SX", "Sint Maarten (Dutch part)"),
            CountryCode("SK", "Slovakia"),
            CountryCode("SI", "Slovenia"),
            CountryCode("SB", "Solomon Islands"),
            CountryCode("SO", "Somalia"),
            CountryCode("ZA", "South Africa"),
            CountryCode("GS", "South Georgia and the South Sandwich Islands"),
            CountryCode("SS", "South Sudan"),
            CountryCode("ES", "Spain"),
            CountryCode("LK", "Sri Lanka"),
            CountryCode("SD", "Sudan"),
            CountryCode("SR", "Suriname"),
            CountryCode("SJ", "Svalbard and Jan Mayen"),
            CountryCode("SE", "Sweden"),
            CountryCode("CH", "Switzerland"),
            CountryCode("SY", "Syria"),
            CountryCode("TW", "Taiwan"),
            CountryCode("TJ", "Tajikistan"),
            CountryCode("TZ", "Tanzania"),
            CountryCode("TH", "Thailand"),
            CountryCode("TL", "Timor-Leste"),
            CountryCode("TG", "Togo"),
            CountryCode("TK", "Tokelau"),
            CountryCode("TO", "Tonga"),
            CountryCode("TT", "Trinidad and Tobago"),
            CountryCode("TN", "Tunisia"),
            CountryCode("TR", "Turkey"),
            CountryCode("TM", "Turkmenistan"),
            CountryCode("TC", "Turks and Caicos Islands"),
            CountryCode("TV", "Tuvalu"),
            CountryCode("UG", "Uganda"),
            CountryCode("UA", "Ukraine"),
            CountryCode("AE", "United Arab Emirates"),
            CountryCode("GB", "United Kingdom"),
            CountryCode("US", "United States"),
            CountryCode("UM", "United States Minor Outlying Islands"),
            CountryCode("UY", "Uruguay"),
            CountryCode("UZ", "Uzbekistan"),
            CountryCode("VU", "Vanuatu"),
            CountryCode("VE", "Venezuela"),
            CountryCode("VN", "Vietnam"),
            CountryCode("VG", "Virgin Islands (British)"),
            CountryCode("VI", "Virgin Islands (U.S.)"),
            CountryCode("WF", "Wallis and Futuna"),
            CountryCode("EH", "Western Sahara"),
            CountryCode("YE", "Yemen"),
            CountryCode("ZM", "Zambia"),
            CountryCode("ZW", "Zimbabwe")
        )
        
        fun fromCode(code: String): CountryCode? {
            return VALID_CODES.find { it.code.equals(code, ignoreCase = true) }
        }
        
        fun isValid(code: String): Boolean {
            return VALID_CODES.any { it.code.equals(code, ignoreCase = true) }
        }
    }
}
